### ISSUE TITLE
Final Problems

### ISSUE THREAD

**Issue by a-wiles** [tedmjablonowski/group-test#11]
Fixing any problems that come from merging branches together.

**Comment by a-wiles** [comment]
Completed format changes for title & plot.
Fixed Local storage to display under the search bar & adjusted plot to now show correctly based upon movie entered.

**Comment by a-wiles** [comment]
Completed final problems including plot length, button space clickable issues and removing unneeded code.

**Comment by Rashiv-Dev** [comment]
Oh wow just now seeing these emails
